### ISSUE TITLE
프로젝트 세팅

### ISSUE THREAD

**Issue by IGhost-P** [NooChuHan/NooChuHan-Frontend-monorepo#1]

**Comment by kimseungdeok** [comment]
@IGhost-P 상우님👻! 현재 이 레포에 여러 브랜치들이 있는데요. 개발을 dev 브랜치에서 진행하면 되는지 확인하고자 코멘트 드립니당. 확인 부탁드립니당. 아래의 사진을 참고 부탁드립니다! 
그리고 stage 브랜치의 역할에 대해서도 알려주시면 감사하겠습니다!


![Image](https://github.com/NooChuHan/NooChuHan-Frontend-monorepo/assets/81807434/a15135ff-b3fa-479f-9ae5-2bee74c36b20)

**Comment by IGhost-P** [comment]
dev - 실제 api가 아닌 test api로 작업
stage - 실제 api로 배포직전 확인하는 작업  ( 현재 백엔드가 없으니 사용하실 필요없습니다)
prod - 실제 배포 -> main으로 작업할 예정 (삭제하겠습니다)
qa - qa 확인용 , stage랑 같아야함 ( 현재는 dev랑 맞추면 됨 )

**Comment by IGhost-P** [comment]
넵 개발은 dev가 중심이고 feature 단위로 작업 부탁드립니다!
브랜치 네이밍은 
기본 규칙
하이픈(-)으로 단어 구분 feature/new-login
소문자, 숫자, 하이픈만 사용 (a-z, 0–9, -)
연속 하이픈은 사용하지 않음 (css 네이밍처럼 feature--new-login로 작성하지 않음)
이름을 하이픈으로 끝내지 않음 feature-new-login-
수행할 작업을 나타내는 설명적이고 간결한 이름 사용
브랜치 접두사
feature/
bugfix/
hotfix/
release/
docs/

로 하겠습니다

**Comment by kimseungdeok** [comment]
오우 확인했습니다!! 감사합니다~ 👻
